
POST http://localhost:3000/eventi
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjJhYWY0MzJiOTEzMjRiYzE0N2EiLCJpYXQiOjE3Mzc0NTUwOTAsImV4cCI6MTczNzQ1ODY5MH0.jUjGYn7bXvtRFnOBtNOTxWChZXPxgakBQdQ-09hnF8M
Content-Type: application/json


{
        "title": "pedalata Solidale",
        "date": "2027-10-05T00:00:00.000Z",
        "location": "teramo",
        "price": 15,
        "target": "Tutti",
        "category": "Sport",
        "description": "non so.",
        "max_subs": "300"
}

###

POST http://localhost:3000/partecipation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjEzMGFmOTJmYzQ5NzU2Nzg3MjgiLCJpYXQiOjE3Mzc4MTY4MzUsImV4cCI6MTczNzgyMDQzNX0.tKHCxOU5czPFwkk7L5fBJcfsD99QPTVoG_uNPPvF-fU
Content-Type: application/json

{"user": "678f6130af92fc4975678728",
  "event": "678f6f61c267f9f09e0dc653"
}

###
POST http://localhost:3000/registration
Content-Type: application/json

{
        "mail": "utente@example.com",
        "password": "admin",
        "name": "admin",
        "dateOfBirth": "1300-11-30T00:00:00.000Z",
        "surname": "admin",
        "telephone": 777
    
}

###
POST http://localhost:3000/access
Content-Type: application/json

{
    "mail": "utente@example.com",
    "password": "securepassword"
}

###
POST http://localhost:3000/control/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjJhYWY0MzJiOTEzMjRiYzE0N2EiLCJpYXQiOjE3Mzc0NTUwOTAsImV4cCI6MTczNzQ1ODY5MH0.jUjGYn7bXvtRFnOBtNOTxWChZXPxgakBQdQ-09hnF8M
Content-Type: application/json

{
    "id": "678f6210af92fc497567873a"
}


###
POST http://localhost:3000/access/token_access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzg1MjI3NWMyOGE5ZDljN2FhNDQ3OWEiLCJpYXQiOjE3MzY4Nzk2MjcsImV4cCI6MTczNjg4MzIyN30.oQ1zHlBvg60jwyPbYx3ablilCrFIhzgRtXwsNlNDTgk
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzg1NGIwOTQwYzQ2ZDhjYWU1YWM3ZDUiLCJpYXQiOjE3MzY3ODk3MzUsImV4cCI6MTczNjc5MzMzNX0.eKriHLfR5Hx6c8TD1RMN-qTu7Z29ThWlPeVq8_dTKLk"
}

###
DELETE http://localhost:3000/control/id?id=678f6223af92fc497567873c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjJhYWY0MzJiOTEzMjRiYzE0N2EiLCJpYXQiOjE3Mzc0NTUwOTAsImV4cCI6MTczNzQ1ODY5MH0.jUjGYn7bXvtRFnOBtNOTxWChZXPxgakBQdQ-09hnF8M
Content-Type: application/json

###
GET http://localhost:3000/eventi/partecipants?id=6785290943a347c53643548d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjJhYWY0MzJiOTEzMjRiYzE0N2EiLCJpYXQiOjE3Mzc0NTUwOTAsImV4cCI6MTczNzQ1ODY5MH0.jUjGYn7bXvtRFnOBtNOTxWChZXPxgakBQdQ-09hnF8M
Content-Type: application/json

###
POST http://localhost:3000/access
Content-Type: application/json

{
  "mail":"admin@example.com",
  "password":"admin"
}

###
GET  http://localhost:3000/control/drafts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjEzMGFmOTJmYzQ5NzU2Nzg3MjgiLCJpYXQiOjE3Mzg2NjQyMTAsImV4cCI6MTczODY2NzgxMH0.rtvG3vmbMGXeU4GNG_7e8BQSVHHCPrE_oWAnKidnEEw
Content-Type: application/json


###
GET http://localhost:3000/eventi/yourEvents?start=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjEzMGFmOTJmYzQ5NzU2Nzg3MjgiLCJpYXQiOjE3Mzc4MTY4MzUsImV4cCI6MTczNzgyMDQzNX0.tKHCxOU5czPFwkk7L5fBJcfsD99QPTVoG_uNPPvF-fU
Content-Type: application/json

###
POST http://localhost:3000/control/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjJhYWY0MzJiOTEzMjRiYzE0N2EiLCJpYXQiOjE3Mzc4MTc4NDgsImV4cCI6MTczNzgyMTQ0OH0.o42h4HD2QHKCmDsPP2iN_hK4KTlVmZ2zzQAghzZCnMQ
Content-Type: application/json

{
  "id":"679120510577256868dc9cd5"
}

###
GET http://localhost:3000/event/filtered?start=0&date="2025-01-01"&title=new
Content-Type: application/json
