
POST http://localhost:3000/event/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjEzMGFmOTJmYzQ5NzU2Nzg3MjgiLCJpYXQiOjE3MzkxOTIzMzIsImV4cCI6MTczOTE5NTkzMn0.uhyNizWfq-GFGf-bkxvc0f9x1MURxwuSGuAib9xsAu0
Content-Type: application/json


{
        "title": "pedalata Solidale",
        "date": "2027-10-05T00:00:00.000Z",
        "location": "teramo",
        "price": 15,
        "target": "Tutti",
        "category": "Sport",
        "description": "non so.",
        "max_subs": 300
}

###

POST http://localhost:3000/partecipation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjEzMGFmOTJmYzQ5NzU2Nzg3MjgiLCJpYXQiOjE3Mzc4MTY4MzUsImV4cCI6MTczNzgyMDQzNX0.tKHCxOU5czPFwkk7L5fBJcfsD99QPTVoG_uNPPvF-fU
Content-Type: application/json

{"user": "678f6130af92fc4975678728",
  "event": "678f6f61c267f9f09e0dc653"
}

###
POST http://localhost:3000/registration
Content-Type: application/json

{
        "mail": "utente@example.com",
        "password": "admin",
        "name": "admin",
        "dateOfBirth": "1300-11-30T00:00:00.000Z",
        "surname": "admin",
        "telephone": 777
    
}

###
POST http://localhost:3000/access
Content-Type: application/json

{
    "mail": "utente@example.com",
    "password": "securepassword"
}

###
POST http://localhost:3000/control/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjJhYWY0MzJiOTEzMjRiYzE0N2EiLCJpYXQiOjE3Mzc0NTUwOTAsImV4cCI6MTczNzQ1ODY5MH0.jUjGYn7bXvtRFnOBtNOTxWChZXPxgakBQdQ-09hnF8M
Content-Type: application/json

{
    "id": "678f6210af92fc497567873a"
}


###
POST http://localhost:3000/access/token_access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzg1MjI3NWMyOGE5ZDljN2FhNDQ3OWEiLCJpYXQiOjE3MzY4Nzk2MjcsImV4cCI6MTczNjg4MzIyN30.oQ1zHlBvg60jwyPbYx3ablilCrFIhzgRtXwsNlNDTgk
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzg1NGIwOTQwYzQ2ZDhjYWU1YWM3ZDUiLCJpYXQiOjE3MzY3ODk3MzUsImV4cCI6MTczNjc5MzMzNX0.eKriHLfR5Hx6c8TD1RMN-qTu7Z29ThWlPeVq8_dTKLk"
}

###
DELETE http://localhost:3000/control/id?id=678f6223af92fc497567873c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjJhYWY0MzJiOTEzMjRiYzE0N2EiLCJpYXQiOjE3Mzc0NTUwOTAsImV4cCI6MTczNzQ1ODY5MH0.jUjGYn7bXvtRFnOBtNOTxWChZXPxgakBQdQ-09hnF8M
Content-Type: application/json

###
GET http://localhost:3000/event/partecipants?id=67a8c542194487f3f523cd28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjJhYWY0MzJiOTEzMjRiYzE0N2EiLCJpYXQiOjE3Mzc0NTUwOTAsImV4cCI6MTczNzQ1ODY5MH0.jUjGYn7bXvtRFnOBtNOTxWChZXPxgakBQdQ-09hnF8M
Content-Type: application/json

###
POST http://localhost:3000/access
Content-Type: application/json

{
  "mail":"admin@example.com",
  "password":"admin"
}

###
GET  http://localhost:3000/control/drafts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjJhYWY0MzJiOTEzMjRiYzE0N2EiLCJpYXQiOjE3MzkxOTM3MzYsImV4cCI6MTczOTE5NzMzNn0.oKPyJRZznQ6AKE0LmXYcCPtgeOWzMea6WvSpkVy5Rdo
Content-Type: application/json


###
GET http://localhost:3000/event/yourDrafts?start=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjJhYWY0MzJiOTEzMjRiYzE0N2EiLCJpYXQiOjE3MzkxOTM3NjIsImV4cCI6MTczOTE5NzM2Mn0.6UtT_4Sqjq238TKr31ztAOnTCLOD79YIjCdP8sJ6WnA

###
POST http://localhost:3000/partecipation/join?event=67a8bf73194487f3f523cc90
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhmNjJhYWY0MzJiOTEzMjRiYzE0N2EiLCJpYXQiOjE3MzkxOTI5OTEsImV4cCI6MTczOTE5NjU5MX0.owW7I1v-ObbOcD3IHgZ-XckKd6uo3eifVquUepZT--E
Content-Type: application/json


###
GET http://localhost:3000/event/filtered?start=0&date="2025-01-01"&title=new
Content-Type: application/json

###
DELETE  http://localhost:3000/delete-old-events
Content-Type: application/json
