GET http://localhost:3000/eventi?price=0&date="2026-11-19"

###

GET http://localhost:3000/eventi

###

GET http://localhost:3000/drafts

###

POST http://localhost:3000/eventi
Content-Type: application/json


{
  "title": "Evento 2",
  "date": "2027-05-25T00:00:00.000Z",
  "location": "siracusa",
  "price": "1",
  "target": "Ragazzi",
  "category": "Sport",
  "description": "esempio",
  "max_subs": "100",
  "organizer": "GroupAppAdmin_3"
}
###

GET http://localhost:3000/eventi/id

###

PATCH http://localhost:3000/eventi/id

###

DELETE  http://localhost:3000/eventi/id

###
GET  http://localhost:3000/

###

POST http://localhost:3000/partecipation
Content-Type: application/json

{"user": "676d6a9da7ca56cf8a048481",
  "event": "676d316e243039a057ef6e37"
}

###
DELETE http://localhost:3000/partecipation/event?eventID=676d316e243039a057ef6e37

###
POST http://localhost:3000/registration
Content-Type: application/json

{
  "mail":"giovanni@pascoli1",
  "userId":"giopascoli1",
  "password":"lepalle",
  "name":"giovanni",
  "dateOfBirth":"2024-11-17T00:00:00.000Z",
  "surname":"pascoli",
  "telephone":333
}

###
POST http://localhost:3000/registration
Content-Type: application/json

{
  "mail": "leonardomosca04@gmail.com",
  "userId": "GroupAppAdmin_3",
  "password": "GroupAppAdmin_3",
  "name": "Groupapp",
  "dateOfBirth": "2004-01-06",
  "surname": "App",
  "telephone": "333"
}


###
POST http://localhost:3000/access
Content-Type: application/json

{
  "mail":"leonardomosca04@gmail.com",
  "password":"GroupAppAdmin_3"
}

###
POST http://localhost:3000/control/id
Content-Type: application/json

{
  "_id":"676d6b2da7ca56cf8a04848c"
 
}


###
POST http://localhost:3000/registration
Content-Type: application/json

{
    "mail": "utente@example.com",
    "userId": "unique_user_123",
    "password": "securepassword",
    "name": "John",
    "dateOfBirth": "1990-01-01T00:00:00.000Z",
    "surname": "Doe",
    "telephone": 1234567890,
    "isAdmin": false
}

###
POST http://localhost:3000/access
Content-Type: application/json

{
    "mail": "utente@example.com",
    "password": "securepassword"
}

###
POST http://localhost:3000/control/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzg1NGIwOTQwYzQ2ZDhjYWU1YWM3ZDUiLCJpYXQiOjE3MzY4Njg4MjUsImV4cCI6MTczNjg3MjQyNX0.ydi2-GDOlPpNHVq5bbMoPb8qIqWIjZ4XaKbD03XCizw
Content-Type: application/json

{
    "id": "676d6b2da7ca56cf8a04848c"
}


###
POST http://localhost:3000/access/token_access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzg1NGIwOTQwYzQ2ZDhjYWU1YWM3ZDUiLCJpYXQiOjE3MzY3ODk3MzUsImV4cCI6MTczNjc5MzMzNX0.eKriHLfR5Hx6c8TD1RMN-qTu7Z29ThWlPeVq8_dTKLk
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzg1NGIwOTQwYzQ2ZDhjYWU1YWM3ZDUiLCJpYXQiOjE3MzY3ODk3MzUsImV4cCI6MTczNjc5MzMzNX0.eKriHLfR5Hx6c8TD1RMN-qTu7Z29ThWlPeVq8_dTKLk"
}

###
DELETE http://localhost:3000/control/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzg1MjI3NWMyOGE5ZDljN2FhNDQ3OWEiLCJpYXQiOjE3MzY4NzMwNjUsImV4cCI6MTczNjg3NjY2NX0.3TaH13kbtoGOeqPTNNhFnU_cekEWZz6Hhtup6notbkc
Content-Type: application/json

{
    "id": "6785287b43a347c53643546c"
}

###
POST http://localhost:3000/eventi/create
Content-Type: application/json

{
    "title": "Event Title",
    "date": "2025-01-20T18:00:00Z",
    "location": "Event Location",
    "price": 100,
    "target": "General Audience",
    "category": "Conference",
    "description": "Event description goes here.",
    "max_subs": 200,
}

### logout tests
POST http://localhost:3000/registration
Content-Type: application/json

{
    "mail": "newuser@example.com",
    "userId": "newuser_123",
    "password": "password123",
    "name": "New",
    "dateOfBirth": "1995-01-01T00:00:00.000Z",
    "surname": "User",
    "telephone": "5551234567"
}

###
POST http://localhost:3000/access
Content-Type: application/json

{
    "mail": "newuser@example.com",
    "password": "password123"
}

###
POST http://localhost:3000/eventi/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzkxMTMyM2I0ZWQ2NjU1MTAwODQwY2QiLCJpYXQiOjE3Mzc1NjI2ODMsImV4cCI6MTczNzU2NjI4M30.ZjRfIJ4S76p3_6NMzkVVpZ4hLa-BXluLiGiDxO0vfoU

{
    "title": "New Event",
    "date": "2025-02-20T18:00:00Z",
    "location": "New Location",
    "price": 50,
    "target": "General Audience",
    "category": "Conference",
    "description": "This is a new event description.",
    "max_subs": 200
    
}

###
POST http://localhost:3000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
POST http://localhost:3000/eventi
Content-Type: application/json
Authorization: Bearer <YOUR_JWT>

{
    "title": "Another Event",
    "date": "2025-03-01T18:00:00Z",
    "location": "Another Location",
    "price": 75,
    "target": "Special Audience",
    "category": "Workshop",
    "description": "This event should fail.",
    "max_subs": 100
}




